controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - rob1_joint_s
      - rob1_joint_l
      - rob1_joint_e
      - rob1_joint_u
      - rob1_joint_r
      - rob1_joint_b
      - rob1_joint_t
  - name: fake_second_manipulator_controller
    joints:
      - rob2_shoulder_pan_joint
      - rob2_shoulder_lift_joint
      - rob2_elbow_joint
      - rob2_wrist_1_joint
      - rob2_wrist_2_joint
      - rob2_wrist_3_joint
  - name: fake_dual_manipulator_controller
    joints:
      - rob1_joint_s
      - rob1_joint_l
      - rob1_joint_e
      - rob1_joint_u
      - rob1_joint_r
      - rob1_joint_b
      - rob1_joint_t
      - rob2_shoulder_pan_joint
      - rob2_shoulder_lift_joint
      - rob2_elbow_joint
      - rob2_wrist_1_joint
      - rob2_wrist_2_joint
      - rob2_wrist_3_joint